CREATE TABLE ENTREGADOR (
ID_ENTREGADOR INTEGER NOT NULL,
NOME_ENTREGADOR VARCHAR2(15) NOT NULL,
IDADE_ENTREGADOR INTEGER NOT NULL,
QTD_ENTREGAS INTEGER NOT NULL,
TELEFONE VARCHAR2(15) NOT NULL,
CONSTRAINT ID_ENTREGADOR_PK PRIMARY KEY (ID_ENTREGADOR)
);

INSERT INTO ENTREGADOR (ID_ENTREGADOR,NOME_ENTREGADOR,IDADE_ENTREGADOR,QTD_ENTREGAS,TELEFONE) VALUES(1,'K99',20,15,'81981770958');
INSERT INTO ENTREGADOR (ID_ENTREGADOR,NOME_ENTREGADOR,IDADE_ENTREGADOR,QTD_ENTREGAS,TELEFONE) VALUES(2,'KYO',18,17,'81981770458');
INSERT INTO ENTREGADOR (ID_ENTREGADOR,NOME_ENTREGADOR,IDADE_ENTREGADOR,QTD_ENTREGAS,TELEFONE) VALUES(3,'IORI',25,20,'81981777558');

SELECT * FROM entregador;

CREATE SEQUENCE SEQUENCE_entregador INCREMENT BY 1 START  WITH 1;

CREATE OR REPLACE TRIGGER TRIGGER_entregador 
BEFORE INSERT ON entregador
FOR EACH ROW 
BEGIN 
SELECT SEQUENCE_entregador.NEXTVAL INTO:NEW.ID_entregador FROM DUAL;
END;

--///////////////////////////////
--///////////////////////////////
--///////////////////////////////
--///////////////////////////////
--///////////////////////////////
--///////////////////////////////
--///////////////////////////////
--///////////////////////////////
--///////////////////////////////
--///////////////////////////////
--///////////////////////////////
--///////////////////////////////
--///////////////////////////////
--///////////////////////////////
--///////////////////////////////
--///////////////////////////////



CREATE TABLE CLIENTE (
ID_CLIENTE INTEGER NOT NULL,
NOME_CLIENTE VARCHAR2(15) NOT NULL,
TELEFONE VARCHAR2(15) NOT NULL,
ENDERECO VARCHAR2(15) NOT NULL,
CONSTRAINT ID_CLIENTE_PK PRIMARY KEY (ID_CLIENTE)
);

INSERT INTO ENTREGADOR (ID_CLIENTE,NOME_CLIENTE,TELEFONE,ENDERECO) VALUES(1,'ZERO','81981770958', 'RUA A');
INSERT INTO ENTREGADOR (ID_CLIENTE,NOME_CLIENTE,TELEFONE,ENDERECO) VALUES(2,'OROCHI','81981770958', 'RUA B');
INSERT INTO ENTREGADOR (ID_CLIENTE,NOME_CLIENTE,TELEFONE,ENDERECO) VALUES(3,'RUGAL','81981770958', 'RUA C');


SELECT * FROM CLIENTE;

DROP TABLE CLIENTE;

CREATE SEQUENCE SEQUENCE_CLIENTE INCREMENT BY 1 START  WITH 1;

CREATE OR REPLACE TRIGGER TRIGGER_CLIENTE
BEFORE INSERT ON CLIENTE
FOR EACH ROW 
BEGIN 
SELECT SEQUENCE_CLIENTE.NEXTVAL INTO:NEW.ID_CLIENTE FROM DUAL;
END;

--///////////////////////////////
--///////////////////////////////
--///////////////////////////////
--///////////////////////////////
--///////////////////////////////
--///////////////////////////////
--///////////////////////////////
--///////////////////////////////
--///////////////////////////////
--///////////////////////////////
--///////////////////////////////
--///////////////////////////////
--///////////////////////////////
--///////////////////////////////

CREATE TABLE VENDAS (
ID_VENDAS INTEGER NOT NULL,
QTD_PIZZAS VARCHAR2(15) NOT NULL,
FORMA_PG VARCHAR2(15) NOT NULL,
ID_ENTREGADOR INTEGER NOT NULL,
ID_CLIENTE INTEGER NOT NULL,
CONSTRAINT ID_VENDAS_PK PRIMARY KEY (ID_VENDAS)
);

INSERT INTO VENDAS (ID_VENDAS,QTD_PIZZAS,FORMA_PG,ID_ENTREGADOR,ID_CLIENTE) VALUES(1,10,'CREDITO');



SELECT * FROM CLIENTE;

DROP TABLE CLIENTE;

CREATE SEQUENCE SEQUENCE_VENDAS INCREMENT BY 1 START  WITH 1;

CREATE OR REPLACE TRIGGER TRIGGER_VENDAS
BEFORE INSERT ON VENDAS
FOR EACH ROW 
BEGIN 
SELECT SEQUENCE_VENDAS.NEXTVAL INTO:NEW.ID_VENDAS FROM DUAL;
END;


ALTER TABLE VENDAS ADD CONSTRAINT ID_ENTREGADOR_FK FOREIGN KEY
(ID_ENTREGADOR)REFERENCES ENTREGADOR (ID_ENTREGADOR);

ALTER TABLE VENDAS ADD CONSTRAINT ID_CLIENTE_FK FOREIGN KEY
(ID_CLIENTE)REFERENCES CLIENTE (ID_CLIENTE);


SELECT 
    NOME_ENTREGADOR,
    QTD_ENTREGAS,
    NOME_CLIENTE, 
    ENDERECO, 
    FORMA_PG
FROM
    ENTREGADOR INNER JOIN VENDAS ON VENDAS.ID_ENTREGADOR = ID_ENTREGADOR.ID_ENTREGADOR;
    
    
SELECT venda.D_VENDAS, venda.QTD_VENDAS, venda.FORMA_PAG, cliente.nome_cliente,cliente.telefone_cliente FROM VENDAS
JOIN CLIENTES
ON  VENDA.id_venda = CLIENTE.id_cliente;

